// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoEZvl-OGV4efbJa3RYCkZFGnUaSQwSSo',
    appId: '1:20856260397:web:2744a500250da0f7c035a4',
    messagingSenderId: '20856260397',
    projectId: 'restoapp-dicoding',
    authDomain: 'restoapp-dicoding.firebaseapp.com',
    storageBucket: 'restoapp-dicoding.appspot.com',
    measurementId: 'G-85HDSMF0J9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn53RhnbO4wA5TaOYd0Fs5fP7kS5zUxiU',
    appId: '1:20856260397:android:0d2224b2585b50a5c035a4',
    messagingSenderId: '20856260397',
    projectId: 'restoapp-dicoding',
    storageBucket: 'restoapp-dicoding.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmnfy_dnpLFVftxKxZCgBlNbkodUG7-aI',
    appId: '1:20856260397:ios:f1aaccb0d44708b5c035a4',
    messagingSenderId: '20856260397',
    projectId: 'restoapp-dicoding',
    storageBucket: 'restoapp-dicoding.appspot.com',
    iosClientId: '20856260397-hnk8p4f9lppb8o1cqk1b5e2iri9skcna.apps.googleusercontent.com',
    iosBundleId: 'com.example.restoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmnfy_dnpLFVftxKxZCgBlNbkodUG7-aI',
    appId: '1:20856260397:ios:f1aaccb0d44708b5c035a4',
    messagingSenderId: '20856260397',
    projectId: 'restoapp-dicoding',
    storageBucket: 'restoapp-dicoding.appspot.com',
    iosClientId: '20856260397-hnk8p4f9lppb8o1cqk1b5e2iri9skcna.apps.googleusercontent.com',
    iosBundleId: 'com.example.restoApp',
  );
}
